# Generated by Django 3.2.9 on 2022-09-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='c1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
